/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Address;
import Model.Contact;
import Model.Person;
import javax.swing.JOptionPane;

/**
 *
 * @author ankithreddy
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    private Person person;
    public MainJFrame() {
        initComponents();
        
        this.person = new Person();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        UserFrontPanel = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        ViewPanel = new javax.swing.JPanel();
        viewName = new javax.swing.JLabel();
        viewStreet = new javax.swing.JLabel();
        viewLastName = new javax.swing.JLabel();
        viewNUID = new javax.swing.JLabel();
        viewCollegeName = new javax.swing.JLabel();
        viewOfficePhone = new javax.swing.JLabel();
        viewPersonalPhone = new javax.swing.JLabel();
        viewOfficeEmail = new javax.swing.JLabel();
        viewPersonalEmail = new javax.swing.JLabel();
        viewCurrentStreet = new javax.swing.JLabel();
        viewPermStreet = new javax.swing.JLabel();
        viewCurrentApt = new javax.swing.JLabel();
        viewPermApt = new javax.swing.JLabel();
        viewCurrentCIty = new javax.swing.JLabel();
        viewPermCIty = new javax.swing.JLabel();
        viewCurrentState = new javax.swing.JLabel();
        viewPermState = new javax.swing.JLabel();
        viewCurrentZip = new javax.swing.JLabel();
        viewPermZip = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UserFrontPanel.setBackground(new java.awt.Color(102, 204, 255));
        UserFrontPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        UserFrontPanel.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 90, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        UserFrontPanel.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 90, 20));

        saveButton.setText("SAVE");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        UserFrontPanel.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        jLabel1.setText("First Name");
        UserFrontPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel2.setText("Street");
        UserFrontPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel3.setText("Last Name");
        UserFrontPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        UserFrontPanel.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 90, -1));

        jLabel4.setText("College Name");
        UserFrontPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
        UserFrontPanel.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 90, -1));

        jLabel5.setText("Contact ");
        UserFrontPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel6.setText("Office");
        UserFrontPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel7.setText("Personal");
        UserFrontPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        jLabel8.setText("Phone");
        UserFrontPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel9.setText("email ID");
        UserFrontPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        UserFrontPanel.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 70, 30));
        UserFrontPanel.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 153, 80, 30));
        UserFrontPanel.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 70, 30));
        UserFrontPanel.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 80, 30));

        jLabel10.setText("Address :");
        UserFrontPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel11.setText("Current");
        UserFrontPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jLabel12.setText("Permanent");
        UserFrontPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));
        UserFrontPanel.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 70, 20));

        jLabel13.setText("Apt. No");
        UserFrontPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel14.setText("City");
        UserFrontPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel15.setText("State");
        UserFrontPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel16.setText("ZipCode");
        UserFrontPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));
        UserFrontPanel.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 80, -1));
        UserFrontPanel.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 80, -1));
        UserFrontPanel.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 80, -1));
        UserFrontPanel.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 80, -1));
        UserFrontPanel.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 80, -1));
        UserFrontPanel.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 80, -1));
        UserFrontPanel.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 80, -1));
        UserFrontPanel.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 80, -1));

        jLabel17.setText("NUID");
        UserFrontPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTextField18.setText("          ");
        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        UserFrontPanel.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 90, -1));

        jSplitPane1.setLeftComponent(UserFrontPanel);

        ViewPanel.setBackground(new java.awt.Color(204, 255, 102));
        ViewPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        ViewPanel.add(viewName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 50, 20));

        viewStreet.setText(".");
        ViewPanel.add(viewStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 50, -1));
        ViewPanel.add(viewLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));
        ViewPanel.add(viewNUID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 20));
        ViewPanel.add(viewCollegeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 60, 20));
        ViewPanel.add(viewOfficePhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        viewPersonalPhone.setText("    ");
        ViewPanel.add(viewPersonalPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        viewOfficeEmail.setText("            ");
        ViewPanel.add(viewOfficeEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        viewPersonalEmail.setText("            ");
        ViewPanel.add(viewPersonalEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        viewCurrentStreet.setText("            ");
        ViewPanel.add(viewCurrentStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        viewPermStreet.setText("          ");
        ViewPanel.add(viewPermStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        viewCurrentApt.setText("            ");
        ViewPanel.add(viewCurrentApt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        viewPermApt.setText("          ");
        ViewPanel.add(viewPermApt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        viewCurrentCIty.setText("            ");
        ViewPanel.add(viewCurrentCIty, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        viewPermCIty.setText("            ");
        ViewPanel.add(viewPermCIty, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        viewCurrentState.setText("           ");
        ViewPanel.add(viewCurrentState, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        viewPermState.setText("         ");
        ViewPanel.add(viewPermState, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        viewCurrentZip.setText("            ");
        ViewPanel.add(viewCurrentZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        viewPermZip.setText("            ");
        ViewPanel.add(viewPermZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        jSplitPane1.setRightComponent(ViewPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        String NUID = jTextField18.getText();
        String firstName = jTextField1.getText();
        String lastName = jTextField3.getText();
        String collegeName = jTextField4.getText();
        String officePhone = jTextField5.getText();
        String personalPhone = jTextField6.getText();
        String officeEmail = jTextField7.getText();
        String PersonalEmail = jTextField8.getText();
        String currentStreet = jTextField2.getText();
        String permStreet = jTextField9.getText();
        String currentApt = jTextField10.getText();
        String permApt = jTextField11.getText();
        String currentCity= jTextField12.getText();
        String permCity= jTextField13.getText();
        String currentState= jTextField14.getText();
        String permState= jTextField15.getText();
        String currentZip = jTextField16.getText();
        String permZip= jTextField17.getText();
               
        
        
      //  String street = jTextField2.getText();
        
        this.person.setFirstName(firstName);
        this.person.setLastName(lastName);
        this.person.setCollegeName(collegeName);
        
        this.person.setNUID(Integer.valueOf(NUID));
        
        
        Contact offCon = this.person.getOffice();
        offCon.setPhone(Integer.valueOf(officePhone));
        offCon.setEmailID(officeEmail);
        
        Contact perCon = this.person.getPersonal();
        perCon.setPhone(Integer.valueOf(personalPhone));
        perCon.setEmailID(PersonalEmail);
        
        
        Address currentAddress = this.person.getCurrentAddress();
        currentAddress.setStreetName(currentStreet);
        currentAddress.setAptNo(currentApt);
        currentAddress.setCity(currentCity);
        currentAddress.setState(currentState);
        currentAddress.setZipCode(Integer.valueOf(currentZip));
        
        Address permAddress = this.person.getPermanentAddress();
        permAddress.setStreetName(permStreet);
        permAddress.setAptNo(permApt);
        permAddress.setCity(permCity);
        permAddress.setState(permState);
        permAddress.setZipCode(Integer.valueOf(permZip));
       
       
        
        
        JOptionPane.showInternalMessageDialog(null, "SAVED SUCCESSFULLY");
        
        display();

    }//GEN-LAST:event_saveButtonActionPerformed

    private void display(){
        viewName.setText(this.person.getFirstName());
        viewLastName.setText(this.person.getLastName());
        viewCollegeName.setText(this.person.getCollegeName());
        
        viewNUID.setText(String.valueOf(this.person.getNUID()));
        
        viewOfficePhone.setText(String.valueOf(this.person.getOffice().getPhone()));
        viewOfficeEmail.setText(this.person.getOffice().getEmailID());
        
        viewPersonalPhone.setText(String.valueOf(this.person.getPersonal().getPhone()));
        viewPersonalEmail.setText(this.person.getPersonal().getEmailID());
        
        viewCurrentStreet.setText(this.person.getCurrentAddress().getStreetName());
        viewCurrentApt.setText(this.person.getCurrentAddress().getAptNo());
        viewCurrentCIty.setText(this.person.getCurrentAddress().getCity());
        viewCurrentState.setText(this.person.getCurrentAddress().getState());
        viewCurrentZip.setText(String.valueOf(this.person.getCurrentAddress().getZipCode()));
        
        
        viewPermStreet.setText(this.person.getPermanentAddress().getStreetName());
        viewPermApt.setText(this.person.getPermanentAddress().getAptNo());
        viewPermCIty.setText(this.person.getPermanentAddress().getCity());
        viewPermState.setText(this.person.getPermanentAddress().getState());
        viewPermZip.setText(String.valueOf(this.person.getPermanentAddress().getZipCode()));
    }
    
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UserFrontPanel;
    private javax.swing.JPanel ViewPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel viewCollegeName;
    private javax.swing.JLabel viewCurrentApt;
    private javax.swing.JLabel viewCurrentCIty;
    private javax.swing.JLabel viewCurrentState;
    private javax.swing.JLabel viewCurrentStreet;
    private javax.swing.JLabel viewCurrentZip;
    private javax.swing.JLabel viewLastName;
    private javax.swing.JLabel viewNUID;
    private javax.swing.JLabel viewName;
    private javax.swing.JLabel viewOfficeEmail;
    private javax.swing.JLabel viewOfficePhone;
    private javax.swing.JLabel viewPermApt;
    private javax.swing.JLabel viewPermCIty;
    private javax.swing.JLabel viewPermState;
    private javax.swing.JLabel viewPermStreet;
    private javax.swing.JLabel viewPermZip;
    private javax.swing.JLabel viewPersonalEmail;
    private javax.swing.JLabel viewPersonalPhone;
    private javax.swing.JLabel viewStreet;
    // End of variables declaration//GEN-END:variables
}
